-- ============================================================
-- Phase 18: agent_memories Schema Updates
-- Adds source column and source_match_id for deduplication.
-- ============================================================

-- source: identifies who/what created the memory.
--   'user'             = manually logged via ingest-memory edge function
--   'agent_reflection' = auto-generated by generate-match-reflection
ALTER TABLE public.agent_memories
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'user';
-- source_match_id: FK to the match that triggered an agent_reflection.
--   Null for user-authored memories.
ALTER TABLE public.agent_memories
  ADD COLUMN IF NOT EXISTS source_match_id uuid REFERENCES public.matches(id) ON DELETE SET NULL;
-- ─── Deduplication Constraint ─────────────────────────────────────────────────
-- Prevents duplicate reflections when the Supabase webhook retries a failed delivery.
-- UNIQUE NULLS NOT DISTINCT: two rows with source_match_id = NULL, same user_id
-- and same source are still considered duplicates (covers edge cases).
ALTER TABLE public.agent_memories
  DROP CONSTRAINT IF EXISTS uq_agent_memories_reflection;
ALTER TABLE public.agent_memories
  ADD CONSTRAINT uq_agent_memories_reflection
  UNIQUE NULLS NOT DISTINCT (user_id, source_match_id, source);
-- ─── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_agent_memories_source
  ON public.agent_memories (source);
CREATE INDEX IF NOT EXISTS idx_agent_memories_source_match
  ON public.agent_memories (source_match_id)
  WHERE source_match_id IS NOT NULL;
-- ─── Verification ─────────────────────────────────────────────────────────────
-- SELECT constraint_name FROM information_schema.table_constraints
-- WHERE table_name = 'agent_memories' AND constraint_name = 'uq_agent_memories_reflection';;
